### ISSUE TITLE
LRC reading strangely

### ISSUE THREAD

**Issue by nullobsi** [eNV25/mpdlrc#41]
Hello!

Thank you for this project, it looks perfect for all I want :)

I have some LRC files that seem to be parsed strangely. I believe it has to do with the fact that repeated lyrics time tags do not come in order in my file, and they are displayed as such in the parser. (might have been a bad explanation)

I noticed on the lrc_test you have the following:

```
[00:12.00][00:13.00][00:14.00]Line 1 lyrics
[00:17.20]Line 2 lyrics
[00:21.10][00:22.00]Line 3 lyrics
```

However, in my file, I have lyrics like the following:

```
[00:12.00][00:18.00][00:20.00]Line 1 lyrics
[00:17.20]Line 2 lyrics
[00:21.10][00:22.00]Line 3 lyrics
```

as in i.e. a chorus that repeats at multiple points in the song. I think the solution is to simply sort by the timestamp in the list? I haven't checked your code.

Also, here's the LRC file that is having issues:
[01 Change.txt](https://github.com/eNV25/mpdlrc/files/12771174/01.Change.txt)

**Comment by eNV25** [comment]
Yea it's just an issue of sorting. The reason I didn't do that is because I wasn't sure if LRC files in the wild actually did that.

**Comment by eNV25** [comment]
I'll add that now.

**Comment by eNV25** [comment]
Does https://github.com/eNV25/mpdlrc/commit/c51d1ef7e73165472fa775acfb2e86ee51f95f4f do it.

**Comment by nullobsi** [comment]
yes, it works fine now, thank you c:
