### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by ghost** [eNV25/mpdlrc#74]
is this thing need a specific font to not look like this?
![scr](https://github.com/user-attachments/assets/82eb5cf9-95a0-4e6d-8e60-cdb8b0861fba)

**Comment by eNV25** [comment]
No specific font. You need a font with that Unicode character. You can also change the character from the source code.

**Comment by eNV25** [comment]
https://github.com/eNV25/mpdlrc/blob/3d79db469322554920a7e8f2a24cd8c384ad0ac9/internal/styles/styles.go#L16-L22

**Comment by ghost** [comment]
yeah its worked right now thanks
